In [1]:
import pandas as pd

In [2]:
url = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user"
users = pd.read_csv(url, sep='|')

Set 'user_id' as index

In [3]:
users = users.set_index('user_id')

See first **rows**

In [4]:
users.head()

         age gender  occupation zip_code
user_id
1         24      M  technician    85711
2         53      F       other    94043
3         23      M      writer    32067
4         24      M  technician    43537
5         33      F       other    15213

Get 'age' column

In [5]:
users['age']

user_id
1      24
2      53
3      23
4      24
5      33
       ..
939    26
940    32
941    20
942    48
943    22
Name: age, Length: 943, dtype: int64

Get multiple columns

In [6]:
users[['age', 'gender', 'occupation']]

         age gender     occupation
user_id
1         24      M     technician
2         53      F          other
3         23      M         writer
4         24      M     technician
5         33      F          other
...      ...    ...            ...
939       26      F        student
940       32      M  administrator
941       20      M        student
942       48      F      librarian
943       22      M        student

[943 rows x 3 columns]

Get row by index (example user_id = 10)

In [7]:
users.loc[10]

age               53
gender             M
occupation    lawyer
zip_code       90703
Name: 10, dtype: object

Get multiple rows

In [8]:
users.loc[[1, 5, 10]]

         age gender  occupation zip_code
user_id
1         24      M  technician    85711
5         33      F       other    15213
10        53      M      lawyer    90703

Filter (age > 30)

In [9]:
users[users['age'] > 30]

         age gender     occupation zip_code
user_id
2         53      F          other    94043
5         33      F          other    15213
6         42      M      executive    98101
7         57      M  administrator    91344
8         36      M  administrator    05201
...      ...    ...            ...      ...
935       42      M         doctor    66221
937       48      M       educator    98072
938       38      F     technician    55038
940       32      M  administrator    02215
942       48      F      librarian    78209

[495 rows x 4 columns]

Filter by multiple conditions

In [10]:
users[(users['age'] > 30) & (users['gender'] == 'M')]

         age gender     occupation zip_code
user_id
6         42      M      executive    98101
7         57      M  administrator    91344
8         36      M  administrator    05201
10        53      M         lawyer    90703
13        47      M       educator    29206
...      ...    ...            ...      ...
932       58      M       educator    06437
934       61      M       engineer    22902
935       42      M         doctor    66221
937       48      M       educator    98072
940       32      M  administrator    02215

[351 rows x 4 columns]

# Select rows & columns together

In [11]:
users.loc[1:10, ['age', 'occupation']]

         age     occupation
user_id
1         24     technician
2         53          other
3         23         writer
4         24     technician
5         33          other
6         42      executive
7         57  administrator
8         36  administrator
9         29        student
10        53         lawyer

iloc (position based)

In [12]:
users.iloc[0:5]

         age gender  occupation zip_code
user_id
1         24      M  technician    85711
2         53      F       other    94043
3         23      M      writer    32067
4         24      M  technician    43537
5         33      F       other    15213

Unique occupations

In [13]:
users['occupation'].unique()

array(['technician', 'other', 'writer', 'executive', 'administrator',
       'student', 'lawyer', 'educator', 'scientist', 'entertainment',
       'programmer', 'librarian', 'homemaker', 'artist', 'engineer',
       'marketing', 'none', 'healthcare', 'retired', 'salesman', 'doctor'],
      dtype=object)

Count occupations

In [14]:
users['occupation'].value_counts()

occupation
student          196
other            105
educator          95
administrator     79
engineer          67
programmer        66
librarian         51
writer            45
executive         32
scientist         31
artist            28
technician        27
marketing         26
entertainment     18
healthcare        16
retired           14
lawyer            12
salesman          12
none               9
homemaker          7
doctor             7
Name: count, dtype: int64

Sort by age

In [15]:
users.sort_values(by='age')

         age gender     occupation zip_code
user_id
30         7      M        student    55436
471       10      M        student    77459
289       11      M           none    94619
674       13      F        student    55337
609       13      F        student    55106
...      ...    ...            ...      ...
559       69      M      executive    10022
767       70      M       engineer    00000
860       70      F        retired    48322
803       70      M  administrator    78212
481       73      M        retired    37771

[943 rows x 4 columns]

BONUS

In [16]:
users.loc[users['age'].idxmax()]

age                73
gender              M
occupation    retired
zip_code        37771
Name: 481, dtype: object